FROM public.ecr.aws/lambda/python:3.10

WORKDIR /var/task

# Upgrade pip
RUN pip install --upgrade pip

# Copy dependencies file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app ./app
COPY main.py .

# Include Mangum to adapt FastAPI to Lambda
RUN pip install mangum

# Correct Lambda handler (FASTAPI + Mangum)
ENTRYPOINT [ "/lambda-entrypoint.sh" ]
CMD [ "main.handler" ]