# === AWS Lambda Dockerfile ===
FROM public.ecr.aws/lambda/python:3.10

WORKDIR /var/task

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY main.py .

RUN pip install mangum

CMD ["main.handler"]
